#!/bin/bash
# LLM_in_Overleaf installer for macOS and Linux (Windows: install.ps1).
# Registers the browser's native messaging host. There is no background service and no port:
# the browser starts the host when the panel needs it and the host exits afterwards.
# Rerun after moving this folder, changing proxy settings or reinstalling a CLI (idempotent).
#   ./install.sh              install or update
#   ./install.sh --uninstall  remove the host registrations and the launcher
set -euo pipefail
cd "$(dirname "$0")"
PROJ="$(pwd)"

# Default ID is for the unpacked build. A store build can authorize its actual ID.
EXT_ID="fabclfbbpmgoojaccbpmopjfkocoaoik"
if [ "${1:-}" = "--extension-id" ]; then
  EXT_ID="${2:-}"
  shift
  [ "$#" -gt 0 ] && shift
fi
if ! [[ "$EXT_ID" =~ ^[a-p]{32}$ ]]; then
  echo "Invalid extension ID: expected exactly 32 letters a-p." >&2
  exit 1
fi
if [ "$#" -gt 0 ] && { [ "$#" -ne 1 ] || [ "$1" != "--uninstall" ]; }; then
  echo "Usage: ./install.sh [--extension-id ID] [--uninstall]" >&2
  exit 1
fi
HOST_NAME="com.llm_in_overleaf.host"
WRAP_DIR="$HOME/.llm_in_overleaf"

case "$(uname -s)" in
  Darwin)
    ROOT="$HOME/Library/Application Support"
    BROWSERS=("Google/Chrome" "Google/Chrome Beta" "Google/Chrome Canary" "Chromium" "Microsoft Edge" "BraveSoftware/Brave-Browser" "Arc/User Data" "Vivaldi")
    ;;
  Linux)
    ROOT="${XDG_CONFIG_HOME:-$HOME/.config}"
    BROWSERS=("google-chrome" "google-chrome-beta" "google-chrome-unstable" "chromium" "microsoft-edge" "BraveSoftware/Brave-Browser" "vivaldi")
    ;;
  *)
    echo "On Windows, run install.ps1 in PowerShell instead."
    exit 1
    ;;
esac

if [ "${1:-}" = "--uninstall" ]; then
  for base in "${BROWSERS[@]}"; do
    target="$ROOT/$base/NativeMessagingHosts/$HOST_NAME.json"
    if [ -f "$target" ]; then rm -f "$target"; echo "  removed $target"; fi
  done
  rm -f "$WRAP_DIR/host.sh"
  echo "LLM_in_Overleaf native host removed. Remove the extension on chrome://extensions."
  echo "Chat sessions created by the CLI stay in ~/.llm_in_overleaf until you delete that folder."
  exit 0
fi

NODE_BIN="$(command -v node || true)"
if [ -z "$NODE_BIN" ]; then
  echo "Node.js was not found. Install Node.js 22.12+ (22.x) or 24+ first (nvm users: open a new terminal or source your shell profile)."
  exit 1
fi
if ! "$NODE_BIN" -e "const [a,b]=process.versions.node.split('.').map(Number);if(!((a===22&&b>=12)||a>=24))process.exit(1)"; then
  echo "Node.js $("$NODE_BIN" --version) is too old. Install Node.js 22.12+ (22.x) or 24+."
  exit 1
fi
"$NODE_BIN" --check "$PROJ/server/native-host.js"

# Browsers start the host without your shell profile, so the launcher records PATH, the CLI
# overrides and the proxy settings of this terminal. Temporary and missing PATH entries are dropped.
clean_path() {
  local out="" dir
  local -a parts
  IFS=':' read -r -a parts <<< "$PATH"
  for dir in "${parts[@]}"; do
    [ -n "$dir" ] && [ -d "$dir" ] || continue
    case "$dir" in
      /tmp/*|/private/tmp/*|/var/folders/*|*/.codex/tmp/*|*/codex-arg0*) continue ;;
    esac
    case ":$out:" in *":$dir:"*) continue ;; esac
    out="${out:+$out:}$dir"
  done
  printf '%s' "$out"
}

mkdir -p "$WRAP_DIR"
ENV_EXPORTS="$(printf 'export PATH=%q' "$(clean_path)")"
for v in http_proxy https_proxy all_proxy no_proxy HTTP_PROXY HTTPS_PROXY ALL_PROXY NO_PROXY \
         LLM_IN_OVERLEAF_CODEX_BIN LLM_IN_OVERLEAF_CLAUDE_BIN LLM_IN_OVERLEAF_TIMEOUT_MS LLM_IN_OVERLEAF_MAX_CHARS CODEX_HOME; do
  val="${!v:-}"
  if [ -n "$val" ]; then
    # Shell-quote captured values; proxy credentials are never printed.
    ENV_EXPORTS="$ENV_EXPORTS
$(printf 'export %s=%q' "$v" "$val")"
  fi
done
{
  printf '#!/bin/bash\n# Generated by LLM_in_Overleaf/install.sh. Rerun the installer to refresh it.\n'
  printf '%s\n' "$ENV_EXPORTS"
  printf 'exec %q %q "$@"\n' "$NODE_BIN" "$PROJ/server/native-host.js"
} > "$WRAP_DIR/host.sh.tmp"
chmod 700 "$WRAP_DIR/host.sh.tmp"
mv "$WRAP_DIR/host.sh.tmp" "$WRAP_DIR/host.sh"

MANIFEST_JSON=$(cat <<EOF
{
  "name": "$HOST_NAME",
  "description": "LLM_in_Overleaf native host (runs the local Claude Code or Codex CLI)",
  "path": "$WRAP_DIR/host.sh",
  "type": "stdio",
  "allowed_origins": ["chrome-extension://$EXT_ID/"]
}
EOF
)

echo "Registering the native messaging host…"
installed=0
for base in "${BROWSERS[@]}"; do
  # Always register Chrome; other Chromium browsers only when they are installed.
  if [ "$base" = "${BROWSERS[0]}" ] || [ -d "$ROOT/$base" ]; then
    dir="$ROOT/$base/NativeMessagingHosts"
    mkdir -p "$dir"
    printf '%s\n' "$MANIFEST_JSON" > "$dir/$HOST_NAME.json"
    echo "  ✓ $dir/$HOST_NAME.json"
    installed=$((installed + 1))
  fi
done

echo "Checking the host…"
"$NODE_BIN" "$PROJ/tools/ping-host.mjs" "$WRAP_DIR/host.sh"

echo ""
echo "✅ LLM_in_Overleaf is installed ($installed browser registration(s))."
echo "Authorized extension ID: $EXT_ID"
echo "If installed from the Chrome Web Store, reload that extension; no Developer mode is required."
echo "For the unpacked development build only:"
echo "  1. Open chrome://extensions, turn on Developer mode, choose Load unpacked and select:"
echo "     $PROJ/extension"
echo "     (Already loaded? Click Reload on the extension card.)"
echo "  2. Open a project on overleaf.com, select LaTeX in Code Editor and click ✦ Rewrite."
echo ""
echo "Uninstall: ./install.sh --uninstall"
