# LLM_in_Overleaf installer for Windows (PowerShell 5.1+). macOS / Linux: use install.sh.
# Registers the browser's native messaging host for the current user. No administrator rights,
# background service or port: the browser starts the host on demand and it exits afterwards.
# Rerun after moving this folder, changing proxy settings or reinstalling a CLI (idempotent).
#   powershell.exe -NoProfile -ExecutionPolicy Bypass -File .\install.ps1              install or update
#   powershell.exe -NoProfile -ExecutionPolicy Bypass -File .\install.ps1 -Uninstall   remove the registration
[CmdletBinding()]
param([switch]$Uninstall)
$ErrorActionPreference = 'Stop'
if ($env:OS -ne 'Windows_NT') { throw 'Use install.sh on macOS or Linux.' }

# The extension ID is fixed by the public key in extension\manifest.json.
$ExtId = 'fabclfbbpmgoojaccbpmopjfkocoaoik'
$HostName = 'com.llm_in_overleaf.host'
$Base = Join-Path $env:LOCALAPPDATA 'LLM_in_Overleaf'
$Launcher = Join-Path $Base 'host.cmd'
$ManifestPath = Join-Path $Base "$HostName.json"
# Chrome is always registered; other Chromium browsers when their settings key exists.
$Browsers = @(
    @{ Parent = 'HKCU:\Software\Google\Chrome'; Always = $true },
    @{ Parent = 'HKCU:\Software\Microsoft\Edge'; Always = $false },
    @{ Parent = 'HKCU:\Software\Chromium'; Always = $false },
    @{ Parent = 'HKCU:\Software\BraveSoftware\Brave-Browser'; Always = $false }
)

if ($Uninstall) {
    foreach ($Browser in $Browsers) {
        $Key = Join-Path $Browser.Parent "NativeMessagingHosts\$HostName"
        if (Test-Path $Key) { Remove-Item -Path $Key -Recurse -Force; Write-Host "  removed $Key" }
    }
    Remove-Item -Path $Launcher, $ManifestPath -Force -ErrorAction SilentlyContinue
    Write-Host 'LLM_in_Overleaf native host removed. Remove the extension on chrome://extensions.'
    Write-Host "Chat sessions created by the CLI stay in $Base until you delete that folder."
    return
}

$Node = (Get-Command node.exe -ErrorAction Stop).Source
& $Node -e "const [a,b]=process.versions.node.split('.').map(Number);if(!((a===22&&b>=12)||a>=24))process.exit(1)"
if ($LASTEXITCODE -ne 0) { throw 'Install Node.js 22.12+ (22.x) or 24+ first.' }
$HostScript = Join-Path $PSScriptRoot 'server\native-host.js'
& $Node --check $HostScript
if ($LASTEXITCODE -ne 0) { throw 'The native host script failed validation.' }
New-Item -ItemType Directory -Force -Path $Base | Out-Null

# Batch files expand %VAR%; double every percent sign and refuse quotes so values stay literal.
function Format-BatchValue([string]$Name, [string]$Value) {
    if ($Value.Contains('"')) { throw "$Name contains a double quote, which the launcher cannot store." }
    return 'set "' + $Name + '=' + $Value.Replace('%', '%%') + '"'
}
$Lines = @('@echo off', 'rem Generated by LLM_in_Overleaf\install.ps1. Rerun the installer to refresh it.')
$Lines += Format-BatchValue 'LLM_IN_OVERLEAF_DATA_DIR' $Base
foreach ($Name in @('HTTP_PROXY', 'HTTPS_PROXY', 'ALL_PROXY', 'NO_PROXY', 'CODEX_HOME', 'LLM_IN_OVERLEAF_TIMEOUT_MS', 'LLM_IN_OVERLEAF_MAX_CHARS')) {
    $Value = [Environment]::GetEnvironmentVariable($Name)
    if ($Value) { $Lines += Format-BatchValue $Name $Value }
}
foreach ($Cli in @('claude', 'codex')) {
    $Key = 'LLM_IN_OVERLEAF_' + $Cli.ToUpperInvariant() + '_BIN'
    $Value = [Environment]::GetEnvironmentVariable($Key)
    if (!$Value) {
        # Prefer native executables; an npm .cmd shim is resolved to its JS entry by server\launch.js.
        $Command = Get-Command "$Cli.exe", "$Cli.cmd" -ErrorAction SilentlyContinue | Select-Object -First 1
        if ($Command) { $Value = $Command.Source }
    }
    if ($Value) { $Lines += Format-BatchValue $Key $Value }
}
$Lines += '"' + $Node + '" "' + $HostScript + '" %*'
if (($Lines -join "`n") -match '[^\x00-\x7F]') {
    # Non-ASCII paths (for example a Chinese user name): switch cmd.exe to UTF-8 before the paths are read.
    $Lines[0] = '@echo off & chcp 65001 >nul'
    [IO.File]::WriteAllText($Launcher, ($Lines -join "`r`n") + "`r`n", (New-Object Text.UTF8Encoding $false))
} else {
    [IO.File]::WriteAllText($Launcher, ($Lines -join "`r`n") + "`r`n", [Text.Encoding]::ASCII)
}

$Manifest = [ordered]@{
    name = $HostName
    description = 'LLM_in_Overleaf native host (runs the local Claude Code or Codex CLI)'
    path = $Launcher
    type = 'stdio'
    allowed_origins = @("chrome-extension://$ExtId/")
}
[IO.File]::WriteAllText($ManifestPath, ($Manifest | ConvertTo-Json -Depth 3), (New-Object Text.UTF8Encoding $false))

Write-Host 'Registering the native messaging host...'
$Registered = 0
foreach ($Browser in $Browsers) {
    if (!$Browser.Always -and !(Test-Path $Browser.Parent)) { continue }
    $Key = Join-Path $Browser.Parent "NativeMessagingHosts\$HostName"
    New-Item -Path $Key -Force | Out-Null
    Set-Item -Path $Key -Value $ManifestPath
    Write-Host "  + $Key"
    $Registered++
}

Write-Host 'Checking the host...'
& $Node (Join-Path $PSScriptRoot 'tools\ping-host.mjs') $Launcher
if ($LASTEXITCODE -ne 0) { throw "The native host did not respond. Launcher: $Launcher" }

Write-Host ''
Write-Host "LLM_in_Overleaf is installed ($Registered browser registration(s))."
Write-Host '  1. Open chrome://extensions, turn on Developer mode, choose Load unpacked and select:'
Write-Host "     $(Join-Path $PSScriptRoot 'extension')"
Write-Host '     (Already loaded? Click Reload on the extension card.)'
Write-Host '  2. Open a project on overleaf.com, select LaTeX in Code Editor and click the Rewrite button.'
Write-Host ''
Write-Host 'Uninstall: powershell.exe -NoProfile -ExecutionPolicy Bypass -File .\install.ps1 -Uninstall'
