#!/bin/bash
# LLM_in_Overleaf 一次性安装脚本：注册 Chrome 原生消息桥。
# 跑完之后【不需要】手动启动任何后端——Chrome 会在插件需要时自动拉起桥程序、用完自动退出。
set -e
if [ "$(uname -s)" != "Darwin" ]; then
  echo "当前安装脚本仅支持 macOS。"
  exit 1
fi
cd "$(dirname "$0")"
PROJ="$(pwd)"

# 插件 ID 由 extension/manifest.json 里的 key 固定，改 key 才会变
EXT_ID="fabclfbbpmgoojaccbpmopjfkocoaoik"
# Keep the native host ID and data path compatible with existing installations.
HOST_NAME="com.overleaf_edit.host"

NODE_BIN="$(command -v node || true)"
if [ -z "$NODE_BIN" ]; then
  echo "❌ 未找到 node。请先安装 Node.js 22.12+（22.x）或 24+（本机 nvm 用户请先 source ~/.zshrc）"
  exit 1
fi

# 1) 桥的启动垫片放在纯 ASCII 路径下（项目路径含中文，垫片里再指回去，稳妥）
WRAP_DIR="$HOME/.overleaf_edit"
mkdir -p "$WRAP_DIR"

# 关键：Chrome 拉起桥进程时不会带 shell 里的代理变量（那些写在 ~/.zshrc 里），
# 而 claude/codex 访问 API 可能必须走代理。所以把"安装这一刻"的代理设置烤进垫片。
# 以后代理端口变了，重跑一次 ./install.sh 即可刷新。
# Shell-quote captured values; never print proxy credentials to the terminal.
ENV_EXPORTS="$(printf 'export PATH=%q\n' "$PATH")"
for v in http_proxy https_proxy all_proxy no_proxy HTTP_PROXY HTTPS_PROXY ALL_PROXY NO_PROXY OVERLEAF_EDIT_CODEX_BIN OVERLEAF_EDIT_CLAUDE_BIN CODEX_HOME; do
  val="${!v}"
  if [ -n "$val" ]; then
    ENV_EXPORTS="$ENV_EXPORTS
$(printf 'export %s=%q' "$v" "$val")"
  fi
done

{
  printf '#!/bin/bash\n# Generated by LLM_in_Overleaf/install.sh\n'
  printf '%s\n' "$ENV_EXPORTS"
  printf 'exec %q %q\n' "$NODE_BIN" "$PROJ/server/native-host.js"
} > "$WRAP_DIR/host.sh"
chmod 700 "$WRAP_DIR/host.sh"

# 2) 把"允许插件连这个桥"的声明写进各浏览器的 NativeMessagingHosts 目录
MANIFEST_JSON=$(cat <<EOF
{
  "name": "$HOST_NAME",
  "description": "LLM_in_Overleaf - Overleaf AI 改写的本机桥（调用 claude/codex CLI）",
  "path": "$WRAP_DIR/host.sh",
  "type": "stdio",
  "allowed_origins": ["chrome-extension://$EXT_ID/"]
}
EOF
)

APPSUP="$HOME/Library/Application Support"
installed=0
write_manifest() {
  local dir="$1"
  mkdir -p "$dir"
  printf '%s\n' "$MANIFEST_JSON" > "$dir/$HOST_NAME.json"
  echo "  ✓ $dir/$HOST_NAME.json"
  installed=$((installed + 1))
}

echo "注册原生消息桥…"
# Chrome 一定写；其余浏览器装了才写
write_manifest "$APPSUP/Google/Chrome/NativeMessagingHosts"
for base in "Google/Chrome Beta" "Google/Chrome Canary" "Chromium" "Microsoft Edge" "BraveSoftware/Brave-Browser" "Arc/User Data"; do
  [ -d "$APPSUP/$base" ] && write_manifest "$APPSUP/$base/NativeMessagingHosts"
done

echo ""
echo "✅ 安装完成（共写入 $installed 处）。接下来："
echo "  1. Chrome 打开 chrome://extensions → 开发者模式 → 加载已解压 → 选 $PROJ/extension"
echo "     （已装过的话点一下扩展的「重新加载」即可）"
echo "  2. 打开 overleaf.com 任意项目，在编辑器里选中一段 LaTeX，点浮标「✦ 改这段」即可"
echo ""
echo "卸载：rm -rf ~/.overleaf_edit 以及各浏览器 NativeMessagingHosts/$HOST_NAME.json"
